version: '3.9'

services:
  php:
    container_name: php
    build: ./docker/php/Dockerfile
    volumes:
      - ./src:/var/www
    depends_on:
      - mysql
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: kazuki6061
      MYSQL_DATABASE: focus
      MYSQL_USER: kazuki
      MYSQL_PASSWORD: 25251061k
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
  phpmyadmin:
    container_name: php-myadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=kazuki
      - PMA_PASSWORD=25251061k
    depends_on:
      - mysql
    ports:
      - 4040:80
    platform: linux/amd64
